### ISSUE TITLE
Settings app constantly freezing and music through Bluetooth now always stopping on events (like plugging in phone to usb that also acts as as aux)

### ISSUE THREAD

**Issue by DeerSpotter** [verygenericname/nathanlr#2]
The phone actually worked really well when I first installed the jailbreak I think like two weeks ago. My settings loaded instantly so fast I was shocked. Now it is loading extremely slow. I think your system files upgrades ruined your first good impression you had. Not sure what you were doing there. 

Don't get me wrong. I love your jailbreak. It is the most amazing thing ever. I just wish I could downgrade the system files so I can tell you which version worked flawlessly. 

![image](https://github.com/user-attachments/assets/bfa4adfc-4455-4cfa-8763-c9168093b890)

**Comment by verygenericname** [comment]
Does this happen in safe mode? the only really change I made is lowering the optimization flag in clang to mostly save battery because it was causing the battery to drain incredibly fast, i also removed a hook left over from serotonin that caused a memory leak

**Comment by verygenericname** [comment]
And it's weird how music pauses like that that does not happen to me or anyone else, you're the first one to my knowledge experiencing that

**Comment by DeerSpotter** [comment]
> Does this happen in safe mode? the only really change I made is lowering the optimization flag in clang to mostly save battery because it was causing the battery to drain incredibly fast, i also removed a hook left over from serotonin that caused a memory leak

Let me test to make sure. I will let you know in a day that way I can make sure.

**Comment by verygenericname** [comment]
I think the lowering the optimization flag from -O3 to -O2 was really good for battery, though ![image](https://github.com/user-attachments/assets/545b43e2-3707-4524-b16d-2bd72fb834cc)

**Comment by DeerSpotter** [comment]
On initial testing safe mode had no issues. I'll run more tests and report back later.

**Comment by verygenericname** [comment]
If it doesn't happen in safemode, it's probably a tweak causing the problem

**Comment by verygenericname** [comment]
Is it any better now

**Comment by DeerSpotter** [comment]
Everything seems to be functioning better

**Comment by verygenericname** [comment]
Thats not possible its at compiler time, I set it to -Os now, hopefully thats better
