### ISSUE TITLE
Wifi disconnecting and reconnecting and battery drain?

### ISSUE THREAD

**Issue by Tgod1991** [verygenericname/nathanlr#3]
Since I updated to 1.8.1-4 I'm experiencing wifi signal dropping and significant battery drain? Was also experiencing this on 1.8.1-2 iPhone 14 iOS 16.6

**Comment by verygenericname** [comment]
WiFi dropping? That's weird. Im not sure about battery drain as i lessened the usage of disk when apps open because I switched to environment variables from storing sandbox extensions on disk. I'm just confused how that causes WiFi dropping out... annoying...

**Comment by Tgod1991** [comment]
> WiFi dropping? That's weird. Im not sure about battery drain as i lessened the usage of disk when apps open because I switched to environment variables from storing sandbox extensions on disk. I'm just confused how that causes WiFi dropping out... annoying...

I can try and screen record and show you but it randomly happens and switches to cellular data then back to wifi I forget what version I was on but since updating to 1.8.1-2 I noticed the issue and now I'm on 1.8.1-4 and issues are persisting. (Maybe the battery drain isn't as bad, I just keep noticing the WiFi problem)

**Comment by verygenericname** [comment]
Is the latest version any better after a while

**Comment by Tgod1991** [comment]
> Is the latest version any better after a while

It does seem much better. Thank you
