### ISSUE TITLE
Question: Is injecting into settings safe unlike roothide or should I use tweaksettings?

### ISSUE THREAD

**Issue by Mukul1127** [verygenericname/nathanlr#7]
title sums it up.

**Comment by verygenericname** [comment]
Yes! its safe. It's injected by default in this jailbreak anyways. The battery usage and Cellular settings work fine.

**Comment by Mukul1127** [comment]
Ok but it's not quite showing up in settings.

**Comment by verygenericname** [comment]
Do you have PreferenceLoader installed?

**Comment by Mukul1127** [comment]
That was it, Jellyfin didn't pull it in for some reason.
